FROM ubuntu:14.04
MAINTAINER Alexandr Krylovskiy "alexandr.krylovskiy@fit.fraunhofer.de"
RUN apt-get update
RUN apt-get install -y wget unzip openjdk-7-jdk
RUN mkdir /opt/lsgc
ENV LSGC_HOME /opt/lsgc
